name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build for GitHub Pages
        run: npm run build
        env:
          NODE_ENV: production
          GITHUB_PAGES: true
        
      - name: Copy platform configuration files
        run: |
          cp ./public/404.html ./dist/404.html
          cp ./public/.nojekyll ./dist/.nojekyll
          cp ./public/vercel.json ./dist/vercel.json
          cp ./public/_redirects ./dist/_redirects
          cp ./public/web.config ./dist/web.config
          cp ./public/.htaccess ./dist/.htaccess
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
